// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRHIxRbtRXpD7njCGCOJSUUaLSLbLqGs',
    appId: '1:241746752545:web:605eeb86049c07b131df60',
    messagingSenderId: '241746752545',
    projectId: 'shopapp-64137',
    authDomain: 'shopapp-64137.firebaseapp.com',
    storageBucket: 'shopapp-64137.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ZLNcKuOc_773G5rD1_AFyPPuMaq-Cwg',
    appId: '1:241746752545:android:eb8186a492e7b1d231df60',
    messagingSenderId: '241746752545',
    projectId: 'shopapp-64137',
    storageBucket: 'shopapp-64137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw6y6UjnnPi3ojBFi7iUBqhK0g00oefGU',
    appId: '1:241746752545:ios:7819b2079dad7ac131df60',
    messagingSenderId: '241746752545',
    projectId: 'shopapp-64137',
    storageBucket: 'shopapp-64137.firebasestorage.app',
    iosBundleId: 'com.example.poketstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw6y6UjnnPi3ojBFi7iUBqhK0g00oefGU',
    appId: '1:241746752545:ios:7819b2079dad7ac131df60',
    messagingSenderId: '241746752545',
    projectId: 'shopapp-64137',
    storageBucket: 'shopapp-64137.firebasestorage.app',
    iosBundleId: 'com.example.poketstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjRHIxRbtRXpD7njCGCOJSUUaLSLbLqGs',
    appId: '1:241746752545:web:a5ae5a861f5de44331df60',
    messagingSenderId: '241746752545',
    projectId: 'shopapp-64137',
    authDomain: 'shopapp-64137.firebaseapp.com',
    storageBucket: 'shopapp-64137.firebasestorage.app',
  );
}
